name: SpellBook
version: '${project.version}'
main: me.viseper.spellbook.SpellBook
api-version: 1.18
authors: [ Viseper ]
description: A book that allows you to cast spells from it.
commands:
  magicMissiles:
    description: Summons a bolt of water
    usage: /magicMissiles
  shockwave:
    description: Creates a shockwave that sends all nearby entities flying away from you
    usage: /shockwave
  shield:
    description: Creates a box of obsidian around you for 5 seconds
    usage: /shield
  sprint:
    description: Gives yourself a short boost in speed, some resistance, and saturation however you can not cast spells or attack while this is active
    usage: /sprint
